options:
  lcm-ssh-key:
    default: 'null'
    type: string
    description: Public SSH key of PLUMgrid LCM which is running PG-Tools
  mgmt-interface:
    type: string
    default:
    description: The interface connected to PLUMgrid Managment network.
  fabric-interfaces:
    default:
    type: string
    description: |
       Interfaces that will provide fabric connectivity on the director nodes.
       Provided in form of json in a string. If no value provided, fabric connnectivity
       will be either mapped using binding or fall back to management network.
  network-device-mtu:
    type: string
    default: '1580'
    description: The MTU size for interfaces managed by director.
  install_sources:
    default: 'ppa:plumgrid-team/stable'
    type: string
    description: Provide the install source from where to install the PLUMgrid debs
  install_keys:
    default: null
    type: string
    description: Provide the respective keys of the install sources
  plumgrid-build:
    default: 'latest'
    type: string
    description: |
       Provide the build version of PLUMgrid packages that needs to be installed
  iovisor-build:
    default: 'latest'
    type: string
    description: |
       Provide the build version of iovisor package that needs to be installed
  metadata-shared-key:
    default: 'plumgrid'
    type: string
    description: Provide a key to be used as the metadata shared key
